### ISSUE TITLE
Agents condition their policy on other agents' actions

### ISSUE THREAD

**Issue by natashamjaques** [eugenevinitsky/sequential_social_dilemma_games#113]
Agents need to be able to choose their next action based on another agent's past action. This way we can assess the causal influence of one agent's action on another. This is necessary before we can do issue #13.

**Comment by eugenevinitsky** [comment]
So, what does this actually entail? It should be part of their state space?

**Comment by natashamjaques** [comment]
Yeah, other agents' actions should be encoded one-hot, and input to each agent in the next timestep. I guess it would be part of their observation space. I was thinking of trying to do this within rllib, but let me know if you think it makes more sense to do within the environment somehow.

**Comment by natashamjaques** [comment]
Moving this to other repo.
