### ISSUE TITLE
A Question about the hyperparameters and MARL

### ISSUE THREAD

**Issue by yurunsheng1** [eugenevinitsky/sequential_social_dilemma_games#148]
Hi, I am wondering whether the Inequity Aversion method and the Social Influence method need extensive hyperparameter sweep to reach a good score?

Also, Do you try any centralized Multi-agent RL methods (like VDN or MADDPG) in the social dilemma environments? do they work well? 

Thank you!

**Comment by joonleesky** [comment]
Actually, I've tried implementing Inequity Aversion method with environments provided by eugenevinisky and it works reasonably well without extensive hyperparameter seep.
However, default hyper parameter setting provided in train_baseline.py was not good enough.

For me, I have not tried the other methods yet.

**Comment by eugenevinitsky** [comment]
Thanks for your input @joonleesky! As for us, we have not tried other methods for these environments; we primarily implemented them to test out the causal reward, and that is fully decentralized whereas MADDPG and VDN is not. Personally, I would love to see the results of using those algorithms on these envs!

**Comment by yurunsheng1** [comment]
Thank you so much! @joonleesky @eugenevinitsky
