### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by justinkterry** [eugenevinitsky/sequential_social_dilemma_games#173]
Hey, I'm working with the environments from this library, and have forked them to make some changes and would like to rerelease them as part of the supplemental materials of my paper. For that to be fully legal, this code would have to be released under an open source license (currently it's under no license). An MIT license is the simplest and easiest to work with in terms of others reusing your code. Could you please add that to this library real quick to make the university IP lawyer happy?

**Comment by eugenevinitsky** [comment]
For sure!

**Comment by eugenevinitsky** [comment]
Done. If you wouldn't mind linking me the paper once it's up, we'll add it a list of projects that use this repo.

**Comment by justinkterry** [comment]
I will, thanks a ton
