### ISSUE TITLE
implementation of the 'communication model'

### ISSUE THREAD

**Issue by lee15253** [eugenevinitsky/sequential_social_dilemma_games#175]
Thanks for the open source code.
In section 5 of the 'Intrinsic Social Motivation via Causal Influence in Multi-Agent RL', there is a communication model with a cheap talk channel. Is it implemented here too? I only found the MOA model.

**Comment by eugenevinitsky** [comment]
Unfortunately we never got that far!

**Comment by lee15253** [comment]
Thank you for the reply. This repo really helpful.
