### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by justinkterry** [eugenevinitsky/sequential_social_dilemma_games#182]
If we use this work in a publication, is there a consistent manner you would like us to cite it with?

**Comment by eugenevinitsky** [comment]
Hmm, I don't have one. @natashamjaques?

**Comment by justinkterry** [comment]
The standard thing to do would be something like this:

@misc{SSDOpenSource,
  author = {[Vinitsky, Eugene and Jaques,  Natasha and Leibo, Joel and Castenada, Antonio and Hughes, Edward]},
  title = {An Open Source Implementation of Sequential Social Dilemma Games},
  year = {2019},
  publisher = {GitHub},
  note = {GitHub repository},
  howpublished = {\url{https://github.com/eugenevinitsky/sequential_social_dilemma_games/issues/182}}
}

**Comment by eugenevinitsky** [comment]
This seems good to me! Thank you for checking!
