### ISSUE TITLE
Colors for orientations

### ISSUE THREAD

**Issue by eugenevinitsky** [eugenevinitsky/sequential_social_dilemma_games#22]
Agents observing other agents need to know which way they are facing.
We need to shade the colors of the agents slightly (or some other scheme) to indicate orientation

**Comment by natashamjaques** [comment]
Hey, they didn't have this in the original environments, meaning agents couldn't tell which way other agents were facing. We could have this in the rendering for humans, but agents shouldn't get to see it.

**Comment by eugenevinitsky** [comment]
Oh interesting, but then they can never know if they're at risk of being hit by a beam? Makes sense to not do this since that's how it is in the paper but I'm curious about this decision.

**Comment by natashamjaques** [comment]
Yeah, it's weird that they're not allowed to see this, but I think we need to stick with how the original environments work for replicability purposes.

**Comment by eugenevinitsky** [comment]
Closed since it's not part of the original papers.
