### ISSUE TITLE
Fix spawn probabilities in cleanup

### ISSUE THREAD

**Issue by eugenevinitsky** [eugenevinitsky/sequential_social_dilemma_games#68]
In cleanup the spawn probabilities seem to not quite work correctly; the waste spawns too fast.

**Comment by eugenevinitsky** [comment]
I think it's correct? Need to check with Edward to see if the understanding of spawn probabilities is correct...
@natashamjaques

**Comment by eugenevinitsky** [comment]
Currently the waste spawning probability is either 0 or 50% which leads to huge jumps. Is this correct?

**Comment by natashamjaques** [comment]
It was not correct - only 1 waste can spawn per timestep
